#!/usr/bin/env php
<?php
define('SWOOLE_JOBS_ROOT_PATH', __DIR__);

// ini_set('default_socket_timeout', -1);
date_default_timezone_set('Asia/Shanghai');

require SWOOLE_JOBS_ROOT_PATH . '/vendor/autoload.php';
$config = require_once SWOOLE_JOBS_ROOT_PATH . '/config.php';

$console = new Kcloze\Jobs\Console($config);
$console->run();
